name: Build
on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]
    workflow_dispatch:
concurrency:
    group: ${{ github.ref }}-build
    cancel-in-progress: true
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: pip install -r requirements.txt
            - uses: actions/setup-node@v4
              with:
                node-version: 20
                cache: npm
            - run: npm ci
            - run: npm run build
              env:
                POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
                POSTGRES_DATABASE: ${{ secrets.POSTGRES_DATABASE }}
                POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
                POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
            - run: aws s3 sync $GITHUB_WORKSPACE/dist s3://$AWS_S3_BUCKET --delete
              env:
                AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                AWS_DEFAULT_REGION: ap-southeast-2
                AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
