name: Build
on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]
    workflow_dispatch:
concurrency:
    group: ${{ github.ref }}-build
    cancel-in-progress: true
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Check me out
              uses: actions/checkout@v4

            - name: Install Python Requirements
              run: pip -m install -r requirements.txt

            - name: Use Node.js
              uses: actions/setup-node@v2

            - name: npm ci, build and test
              run: |
                npm ci
                npm run build --if-present

            - name: Publish to Cloudflare
              uses: cloudflare/pages-action@v1
              with:
                apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
                accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
                projectName: ${{ secrets.CLOUDFLARE_PAGES }}
                directory: 'dist'
                gitHubToken: ${{ secrets.GITHUB_TOKEN }}
